locator:str="https://atid.store/"
locator1: str="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[2]/a[1]"
locator2:str="//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[1]/div[1]/a[1]/img[1]"
locator3:str="//button[contains(text(),'Add to cart')]"
locator4:str="//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
locator5:str="//a[contains(text(),'Anchor Bracelet')]"
locator6:str="Anchor Bracelet"
locator11:str="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[3]/a[1]"
locator22:str="//a[contains(text(),'→')]"
locator33:str="//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[1]"
locator44:str="//button[contains(text(),'Add to cart')]"
locator55:str="//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
locator66:str="//a[contains(text(),'Green Hoodie')]"
locator77:str="Green Hoodie"
locator12:str="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[4]/a[1]"
locator13:str="//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[10]/div[1]/a[1]/img[1]"
locator14:str="//button[contains(text(),'Add to cart')]"
locator15:str="//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
locator16:str="//a[contains(text(),'Buddha Bracelet')]"
locator17:str="Buddha Bracelet"
locator18:str='//header/div[@id="ast-desktop-header"]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[5]/a[1]'
locator19:str='//body/div[@id="page"]/div[@id="content"]/div[1]/div[2]/main[1]/div[1]/ul[1]/li[3]/div[1]/a[1]/img[1]'
locator20:str='//button[contains(text(),"Add to cart")]'
locator21:str="//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
locator222:str="//input[@id='coupon_code']"
locator34:str="bizu123"
locator35:str="//button[contains(text(),'Apply coupon')]"
locator36:str="//li[contains(text(),Coupon 'bizu123' does not exist!)]"
locator37:str="Coupon 'bizu123' does not exist!"